name: esearch
on: 
  push:
    branches: [main, dev, testing-actions]
  schedule:
    - cron: '0 5 * * *'

jobs:
  esearch:
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run:  "echo testing 1 2 3"

