name: esearch
on: 
  push:
    branches: [main, dev, testing-actions]
  schedule:
    - cron: '0 5 * * *'

env:
  ACC: "SAMN14938803"

jobs:
  esearch:
    runs-on: ubuntu-18.04
    steps:
      - name: apt-get
        run:  |
          sudo apt-get install -y ncbi-entrez-direct tree ca-certificates
      - name: esearch
        run:  |
          esearch -db biosample -query "${{ env.ACC }}" >  ${{ env.ACC }}.xml
          cat ${{ env.ACC }}
      - name: efetch biosample
        run:  |
          cat SAMN14938803.xml | efetch > SAMN14938803.txt
          cat SAMN14938803.txt
          grep SAMN14938803 SAMN14938803.txt
      - name: efetch nucleotide
        run:  |
          cat SAMN14938803.xml | elink -target nucleotide > SAMN14938803.nucl.xml
          cat SAMN14938803.nucl.xml | xtract -format
      - name: efetch fasta
        run:
          cat SAMN14938803.nucl.xml | efetch -format fasta

