name: esearch
on: 
  push:
    branches: [main, dev, testing-actions]
  schedule:
    - cron: '0 5 * * *'

jobs:
  esearch:
    runs-on: ubuntu-18.04
    steps:
      - name: apt-get
        run:  |
          sudo apt-get install -y sra-toolkit tree
      - name: esearch
        run:  |
          esearch -db biosample -query "SAMN14938803" >  SAMN14938803.xml
          cat SAMN14938803.xml
